FROM rocketchat/base:8


RUN sudo apt install g++ build-essential git curl python-minimal

RUN curl https://install.meteor.com/ | sh

ADD . /app

RUN chown -R rocketchat:rocketchat /app

USER rocketchat

WORKDIR /app

RUN meteor npm install

# needs a mongoinstance - defaults to container linking with alias 'mongo'
ENV NODE_ENV=development \
    MONGO_URL=mongodb://mongo:27017/rocketchat \
    PORT=3000 \
    ROOT_URL=http://localhost:3000 \
    Accounts_AvatarStorePath=/app/uploads \
    TOOL_NODE_FLAGS=--max-old-space-size=8192 \
    NODE_OPTIONS=--max-old-space-size=8192

EXPOSE 3000

CMD meteor npm start


