FROM node:10.13

RUN apt-get update

RUN apt install -y g++ build-essential git curl python-minimal ca-certificates imagemagick --no-install-recommends
# && groupadd -g 65533 -r rocketchat \
# && useradd -u 65533 -r -g rocketchat rocketchat

# RUN curl https://install.meteor.com/ | sh



# RUN curl https://install.meteor.com/ | sed 's/1.8.2/1.6.1/' | sh


RUN useradd -ms /bin/bash rocketchat

ADD . /home/rocketchat/app

WORKDIR /home/rocketchat/app


# USER rocketchat

# RUN mkdir /home
RUN mkdir /home/rocketchat/.meteor-install-tmp

RUN chown -Rh rocketchat:rocketchat /home/rocketchat/app

USER rocketchat

RUN meteor npm install

RUN chown -Rh rocketchat:rocketchat /home/rocketchat/app


# needs a mongoinstance - defaults to container linking with alias 'mongo'

ENV NODE_ENV=development \
    MONGO_URL=mongodb://mongo:27017/rocketchat \
    PORT=3000 \
    ROOT_URL=http://localhost:3000 \
    Accounts_AvatarStorePath=/app/uploads \
    TOOL_NODE_FLAGS=--max-old-space-size=8192 \
    NODE_OPTIONS=--max-old-space-size=8192

EXPOSE 3000

CMD meteor npm start